[{"slug":"1.2i","name":"1.2i","trim":"1.2i","body":null,"generation":"T300"},{"slug":"1.3D","name":"1.3D","trim":"1.3D","body":null,"generation":"T300"},{"slug":"1.4 Turbo","name":"1.4 Turbo","trim":"1.4 Turbo","body":null,"generation":"T300"},{"slug":"1.4i","name":"1.4i","trim":"1.4i","body":null,"generation":"T300"},{"slug":"1.5i","name":"1.5i","trim":"1.5i","body":null,"generation":"T250"},{"slug":"1.6i","name":"1.6i","trim":"1.6i","body":null,"generation":"T300"}]